# Generated by Django 2.2.19 on 2022-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformapp', '0002_auto_20221024_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='module_file',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='subject_file',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='topic_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
