# Generated by Django 2.2.19 on 2022-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformapp', '0003_auto_20221024_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseform',
            name='module_file',
            field=models.FileField(upload_to='modfile'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='subject_file',
            field=models.FileField(upload_to='subfile'),
        ),
        migrations.AlterField(
            model_name='courseform',
            name='topic_file',
            field=models.FileField(upload_to='topfile'),
        ),
    ]
